# Generated by Django 5.2.7 on 2025-12-06 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_TASK', 'Create Task'), ('UPDATE_TASK', 'Update Task'), ('DELETE_TASK', 'Delete Task'), ('ASSIGN_USER', 'Assign User'), ('COMPLETE_TASK', 'Complete Task'), ('PASSWORD_RESET', 'Password Reset'), ('CREATE_PROJECT', 'Create Project'), ('CREATE_TEAM', 'Create Team')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
